version: "3.8"

services:
  web:
    build:
      context: ./frontend
      target: runner
    container_name: nextjs
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    restart: unless-stopped
    depends_on:
      - pocketbase
  pocketbase:
    image: augustodelg/pocketbase:latest
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - pocketbase-data:/pb_data
      - pocketbase-data:/pb_migrations
volumes:
  pocketbase-data:
