version: "3.8"

services:
  web:
   build:
     context: ./frontend
     target: runner
   container_name: nextjs
   volumes:
     - ./frontend:/app
     - /app/node_modules
   ports:
     - "3000:3000"
   environment:
      - NODE_ENV=development

      # Set to true if developing on Windows
      - NEXT_WEBPACK_USEPOLLING=false
   restart: unless-stopped

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    working_dir: /var/www/
    user: 1000:1000
    volumes:
      - ./backend:/var/www
      - ./backend/php.ini:/usr/local/etc/php/php.ini
    networks:
      - bridge

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: laravel
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - bridge

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - bridge

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www
      - ./backend/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - bridge
    depends_on:
      - php

networks:
  bridge:
    driver: bridge
